includes += \
	-I$(ROOT)/apps/common/third_party_profile/jieli/trans_data_demo/ \

objs += \
	$(ROOT)/apps/$(APP_CASE)/third_party_profile/trans_data_demo/trans_data_demo.o \
	$(ROOT)/apps/$(APP_CASE)/third_party_profile/ancs_client_demo/ancs_client_demo.o \

objs += \
	$(ROOT)/apps/$(APP_CASE)/third_party_profile/app_protocol_deal.o \


