objs += \
    $(ROOT)/apps/common/third_party_profile/interface/app_protocol_api.o \
    $(ROOT)/apps/common/third_party_profile/interface/app_protocol_ota.o \
    $(ROOT)/apps/common/third_party_profile/interface/app_protocol_common.o \
	$(ROOT)/apps/common/third_party_profile/interface/app_protocol_gma.o \
	$(ROOT)/apps/common/third_party_profile/interface/app_protocol_dma.o \
	$(ROOT)/apps/common/third_party_profile/interface/app_protocol_mma.o \
	$(ROOT)/apps/common/third_party_profile/interface/app_protocol_tme.o \

